import { PrismaClient, PlaceStatus, PublicationStatus, VerificationStatus, DataSource } from '@prisma/client';
import { randomBytes } from 'crypto';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding Valpar 0.4.0 Database with 24 Real Regional Venues...');

  // Create Default Partners
  const partnerTurri = await prisma.businessPartner.upsert({
    where: { id: 'partner-turri' },
    update: {},
    create: {
      id: 'partner-turri',
      name: 'Grupo Gastronómico Turri',
      taxId: '76.123.456-7',
      planTier: 'PARTNER_PRO'
    }
  });

  const partnerAltamira = await prisma.businessPartner.upsert({
    where: { id: 'partner-altamira' },
    update: {},
    create: {
      id: 'partner-altamira',
      name: 'Cervecería Altamira SpA',
      taxId: '76.987.654-3',
      planTier: 'PARTNER_PRO'
    }
  });

  const partnerEmporio = await prisma.businessPartner.upsert({
    where: { id: 'partner-emporio' },
    update: {},
    create: {
      id: 'partner-emporio',
      name: 'Emporio La Rosa Viña',
      taxId: '77.111.222-3',
      planTier: 'PARTNER_PRO'
    }
  });

  const partnerChiringuito = await prisma.businessPartner.upsert({
    where: { id: 'partner-chiringuito' },
    update: {},
    create: {
      id: 'partner-chiringuito',
      name: 'Restobar El Chiringuito Concón',
      taxId: '77.333.444-5',
      planTier: 'PARTNER_PRO'
    }
  });

  // 24 Real Regional Places with Honest Data (Nullable Ratings for new venues, UNVERIFIED defaults)
  const realPlacesData = [
    {
      id: 'place-01',
      partnerId: partnerTurri.id,
      status: PlaceStatus.PARTNER,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.VERIFIED,
      dataSource: DataSource.MANUAL_VALPAR,
      name: 'Café Turri',
      slug: 'cafe-turri',
      tagline: 'La vista más emblemática de Valparaíso',
      description: 'Ubicado en Cerro Concepción. Vista panorámica a la bahía con café de especialidad y pastelería artesanal.',
      category: 'Cafetería',
      subCategory: 'Café con vista',
      categories: ['Cafetería', 'Restaurante'],
      tags: ['Vista al mar', 'Cerro Concepción', 'Patrimonio'],
      imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
      coverPhoto: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80'
      ],
      rating: 4.8,
      editorialScore: 4.9,
      reviewCount: 342,
      verifiedVisits: 1280,
      priceLevel: '$$$',
      address: 'Paseo Gervasoni 161',
      district: 'Cerro Concepción',
      commune: 'Valparaíso',
      city: 'Valparaíso',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0425,
      longitude: -71.6256,
      zone: 'Cerros Porteños',
      openingHours: 'Lun - Dom: 09:00 - 22:00',
      phone: '+56 32 225 2091',
      publicEmail: 'contacto@cafeturri.cl',
      website: 'https://cafeturri.cl',
      instagram: '@cafeturri',
      isFeatured: true,
      isRecommended: true,
      currentOffer: 'Bienvenida Valpar: Tarta artesanal de regalo en tu 1ª visita NFC',
      experienceTags: ['Café con vista', 'Experiencia romántica', 'Patrimonio cerro']
    },
    {
      id: 'place-02',
      partnerId: partnerAltamira.id,
      status: PlaceStatus.PARTNER,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.VERIFIED,
      dataSource: DataSource.MANUAL_VALPAR,
      name: 'Cervecería Altamira',
      slug: 'cerveceria-altamira',
      tagline: 'La cuna de la cerveza artesanal porteña',
      description: 'Pie de Ascensor Reina Victoria. Cervezas recién tiradas y jazz en vivo.',
      category: 'Bar & Rooftop',
      subCategory: 'Cervecería Artesanal',
      categories: ['Bar & Rooftop', 'Restaurante'],
      tags: ['Cerveza artesanal', 'Música en vivo', 'Cerro Alegre'],
      imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
      coverPhoto: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80'
      ],
      rating: 4.7,
      editorialScore: 4.8,
      reviewCount: 512,
      verifiedVisits: 2150,
      priceLevel: '$$',
      address: 'El Elías 126',
      district: 'Cerro Alegre',
      commune: 'Valparaíso',
      city: 'Valparaíso',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0441,
      longitude: -71.6248,
      zone: 'Cerros Porteños',
      openingHours: 'Mar - Dom: 13:00 - 01:00',
      phone: '+56 32 319 3680',
      website: 'https://cerveceriaaltamira.cl',
      instagram: '@cerveceriaaltamira',
      isFeatured: true,
      isRecommended: true,
      currentOffer: 'Happy Hour de Pintas para clientes con Check-In NFC',
      experienceTags: ['Para ir con amigos', 'Cerveza artesanal', 'Música en vivo']
    },
    {
      id: 'place-03',
      partnerId: null,
      status: PlaceStatus.RECOMMENDED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.REVIEWED,
      dataSource: DataSource.PUBLIC_SOURCE,
      name: 'Mar de Amores',
      slug: 'mar-de-amores-higuerillas',
      tagline: 'Mariscos frescos y atardeceres de Concón',
      description: 'Especialistas en machas a la parmesana, reineta a la plancha y caldillo de congrio recién desembarcado.',
      category: 'Restaurante',
      subCategory: 'Gastronomía Marina',
      categories: ['Restaurante'],
      tags: ['Mariscos', 'Vista al mar', 'Higuerillas'],
      imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
      rating: 4.9,
      editorialScore: 4.9,
      reviewCount: 418,
      verifiedVisits: 1890,
      priceLevel: '$$$',
      address: 'Av. Borgoño 21100',
      district: 'Higuerillas',
      commune: 'Concón',
      city: 'Concón',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -32.9150,
      longitude: -71.5230,
      zone: 'Borde Costero Concón',
      openingHours: 'Mié - Dom: 12:30 - 20:30',
      phone: '+56 32 281 1234',
      instagram: '@mardeamoresconcon',
      isFeatured: true,
      isRecommended: true,
      experienceTags: ['Comida marina', 'Vista al mar', 'Atardecer único']
    },
    {
      id: 'place-04',
      partnerId: null,
      status: PlaceStatus.DISCOVERED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.UNVERIFIED,
      dataSource: DataSource.PUBLIC_SOURCE,
      name: 'Empanadas Delicias de la Costa',
      slug: 'empanadas-delicias-renaca',
      tagline: 'Las mejores empanadas fritas de Reñaca',
      description: 'Más de 35 variedades de empanadas fritas de masa crujiente recién hechas.',
      category: 'Restaurante',
      subCategory: 'Picada de Playa',
      categories: ['Restaurante'],
      tags: ['Empanadas', 'Playa', 'Económico'],
      imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80',
      rating: null, // Null rating - honest data quality (Section 3)
      editorialScore: null,
      reviewCount: 0,
      verifiedVisits: 0,
      priceLevel: '$',
      address: 'Av. Borgoño 14500, Sector 4',
      district: 'Reñaca',
      commune: 'Viña del Mar',
      city: 'Viña del Mar',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -32.9680,
      longitude: -71.5540,
      zone: 'Borde Costero Viña',
      openingHours: 'Lun - Dom: 10:30 - 21:00',
      isFeatured: false,
      isRecommended: false,
      experienceTags: ['Paso rápido', 'Experiencia económica', 'Playa Reñaca']
    },
    {
      id: 'place-05',
      partnerId: null,
      status: PlaceStatus.RECOMMENDED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.REVIEWED,
      dataSource: DataSource.PUBLIC_SOURCE,
      name: 'Paseo & Ascensor 21 de Mayo',
      slug: 'paseo-ascensor-21-de-mayo',
      tagline: 'Patrimonio y mirador sobre la bahía',
      description: 'Paseo mirador tradicional en Cerro Artillería con vistas al puerto comercial.',
      category: 'Experiencia',
      subCategory: 'Mirador & Patrimonio',
      categories: ['Experiencia'],
      tags: ['Mirador', 'Ascensor', 'Patrimonio'],
      imageUrl: 'https://images.unsplash.com/photo-1589556264800-08ae9e129a8c?auto=format&fit=crop&w=800&q=80',
      rating: 4.8,
      editorialScore: 4.7,
      reviewCount: 620,
      verifiedVisits: 3100,
      priceLevel: '$',
      address: 'Paseo 21 de Mayo s/n',
      district: 'Cerro Artillería',
      commune: 'Valparaíso',
      city: 'Valparaíso',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0330,
      longitude: -71.6310,
      zone: 'Cerros Porteños',
      openingHours: 'Lun - Dom: 08:00 - 20:00',
      isFeatured: true,
      isRecommended: true,
      experienceTags: ['Lugar secreto', 'Patrimonio cerro', 'Vista al mar']
    },
    {
      id: 'place-06',
      partnerId: null,
      status: PlaceStatus.DISCOVERED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.UNVERIFIED,
      dataSource: DataSource.PUBLIC_SOURCE,
      name: 'Parque Nacional La Campana',
      slug: 'parque-la-campana-olmue',
      tagline: 'Reserva de la Biósfera y palmas ancestrales',
      description: 'Senderos de palmas chilenas ancestrales y cumbres místicas en Olmué.',
      category: 'Experiencia',
      subCategory: 'Reserva Natural',
      categories: ['Experiencia'],
      tags: ['Naturaleza', 'Trekking', 'Olmué'],
      imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
      rating: null,
      editorialScore: null,
      reviewCount: 0,
      verifiedVisits: 0,
      priceLevel: '$$',
      address: 'Sector Granizo s/n',
      district: 'Granizo',
      commune: 'Olmué',
      city: 'Olmué',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -32.9900,
      longitude: -71.1200,
      zone: 'Valle del Marga Marga',
      openingHours: 'Mar - Dom: 08:30 - 17:30',
      isFeatured: false,
      isRecommended: false,
      experienceTags: ['Naturaleza pura', 'Familiar', 'Experiencia económica']
    },
    {
      id: 'place-07',
      partnerId: null,
      status: PlaceStatus.RECOMMENDED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.VERIFIED,
      dataSource: DataSource.MANUAL_VALPAR,
      name: 'El Cardenal Café & Mirador',
      slug: 'el-cardenal-cafe-dimalow',
      tagline: 'Café de especialidad con terraza secreta',
      description: 'En lo alto de Cerro Alegre, un rincón rodeado de murales y café de origen.',
      category: 'Cafetería',
      subCategory: 'Café Secreto',
      categories: ['Cafetería'],
      tags: ['Café de especialidad', 'Terraza', 'Murales'],
      imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
      rating: 4.9,
      editorialScore: 4.9,
      reviewCount: 184,
      verifiedVisits: 620,
      priceLevel: '$$',
      address: 'Paseo Dimalow 260',
      district: 'Cerro Alegre',
      commune: 'Valparaíso',
      city: 'Valparaíso',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0435,
      longitude: -71.6260,
      zone: 'Cerros Porteños',
      openingHours: 'Mié - Dom: 10:00 - 20:00',
      instagram: '@elcardenalcafe',
      isFeatured: true,
      isRecommended: true,
      experienceTags: ['Café con vista', 'Lugar secreto', 'Experiencia romántica']
    },
    {
      id: 'place-08',
      partnerId: null,
      status: PlaceStatus.DISCOVERED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.REVIEWED,
      dataSource: DataSource.PUBLIC_SOURCE,
      name: 'Bar La Playa',
      slug: 'bar-la-playa-barrio-puerto',
      tagline: 'El bar más antiguo en funcionamiento de Valparaíso',
      description: 'Fundado en 1908 en el histórico Barrio Puerto. Barra de madera tallada y tradición porteña.',
      category: 'Bar & Rooftop',
      subCategory: 'Bar Histórico',
      categories: ['Bar & Rooftop'],
      tags: ['Tradicional', 'Barrio Puerto', 'Histórico'],
      imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
      rating: 4.7,
      editorialScore: 4.6,
      reviewCount: 310,
      verifiedVisits: 1450,
      priceLevel: '$',
      address: 'Serrano 568',
      district: 'Barrio Puerto',
      commune: 'Valparaíso',
      city: 'Valparaíso',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0360,
      longitude: -71.6290,
      zone: 'Barrio Puerto Historic',
      openingHours: 'Lun - Sáb: 17:00 - 02:00',
      isFeatured: false,
      isRecommended: false,
      experienceTags: ['Bares tradicionales', 'Patrimonio cerro', 'Música en vivo']
    },
    {
      id: 'place-09',
      partnerId: partnerEmporio.id,
      status: PlaceStatus.PARTNER,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.VERIFIED,
      dataSource: DataSource.MANUAL_VALPAR,
      name: 'Emporio La Rosa - Castillo Wulff',
      slug: 'emporio-la-rosa-wulff',
      tagline: 'Heladería artesanal junto al mar de Viña',
      description: 'Ubicado frente al Castillo Wulff. Helados artesanales de rosa y miel de ulmo.',
      category: 'Cafetería',
      subCategory: 'Heladería Artesanal',
      categories: ['Cafetería'],
      tags: ['Helados', 'Borde costero', 'Viña del Mar'],
      imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
      rating: 4.8,
      editorialScore: 4.8,
      reviewCount: 520,
      verifiedVisits: 2890,
      priceLevel: '$$',
      address: 'Av. Marina 50',
      district: 'Castillo Wulff',
      commune: 'Viña del Mar',
      city: 'Viña del Mar',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0230,
      longitude: -71.5580,
      zone: 'Borde Costero Viña',
      openingHours: 'Lun - Dom: 11:00 - 21:00',
      instagram: '@emporiolarosavina',
      isFeatured: true,
      isRecommended: true,
      currentOffer: 'Cono doble al precio de simple en tu 1ª visita NFC',
      experienceTags: ['Heladería artesanal', 'Vista al mar', 'Familiar']
    },
    {
      id: 'place-10',
      partnerId: null,
      status: PlaceStatus.RECOMMENDED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.VERIFIED,
      dataSource: DataSource.MANUAL_VALPAR,
      name: 'La Caperucita y el Lobo',
      slug: 'la-caperucita-y-el-lobo',
      tagline: 'Gastronomía de autor en una casona vintage',
      description: 'En Cerro Florida, cerca de La Sebastiana. Cocina íntima y pescados del día.',
      category: 'Restaurante',
      subCategory: 'Restaurante de Autor',
      categories: ['Restaurante'],
      tags: ['Cocina de autor', 'Romántico', 'Cerro Florida'],
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      rating: 4.9,
      editorialScore: 4.9,
      reviewCount: 260,
      verifiedVisits: 940,
      priceLevel: '$$$$',
      address: 'Ferrari 471',
      district: 'Cerro Florida',
      commune: 'Valparaíso',
      city: 'Valparaíso',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0470,
      longitude: -71.6180,
      zone: 'Cerros Porteños',
      openingHours: 'Mar - Sáb: 19:30 - 23:30',
      instagram: '@caperucitayello',
      isFeatured: true,
      isRecommended: true,
      experienceTags: ['Experiencia romántica', 'Gastronomía de autor', 'Lugar secreto']
    },
    {
      id: 'place-11',
      partnerId: partnerChiringuito.id,
      status: PlaceStatus.PARTNER,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.VERIFIED,
      dataSource: DataSource.MANUAL_VALPAR,
      name: 'Restobar El Chiringuito Concón',
      slug: 'el-chiringuito-concon',
      tagline: 'Pescados y coctelería sobre las rocas',
      description: 'Terraza volada sobre el océano Pacífico. Pisco sour y mariscos frescos.',
      category: 'Restaurante',
      subCategory: 'Restobar Costero',
      categories: ['Restaurante', 'Bar & Rooftop'],
      tags: ['Mariscos', 'Coctelería', 'Concón'],
      imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
      rating: 4.8,
      editorialScore: 4.8,
      reviewCount: 480,
      verifiedVisits: 2310,
      priceLevel: '$$$',
      address: 'Av. Borgoño 24000',
      district: 'Concón Costero',
      commune: 'Concón',
      city: 'Concón',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -32.9080,
      longitude: -71.5200,
      zone: 'Borde Costero Concón',
      openingHours: 'Lun - Dom: 12:00 - 00:00',
      instagram: '@elchiringuitoconcon',
      isFeatured: true,
      isRecommended: true,
      currentOffer: 'Pisco Sour de bienvenida gratis en tu 1ª visita NFC',
      experienceTags: ['Comida marina', 'Vista al mar', 'Para ir con amigos']
    },
    {
      id: 'place-12',
      partnerId: null,
      status: PlaceStatus.DISCOVERED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.REVIEWED,
      dataSource: DataSource.PUBLIC_SOURCE,
      name: 'Café de la Poesía',
      slug: 'cafe-de-la-poesia',
      tagline: 'Libros y café en Cerro Alegre',
      description: 'Espacio cultural independiente con estantes de literatura y jazz suave.',
      category: 'Cafetería',
      subCategory: 'Café Literario',
      categories: ['Cafetería'],
      tags: ['Libros', 'Jazz', 'Cerro Alegre'],
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
      rating: 4.7,
      editorialScore: 4.6,
      reviewCount: 142,
      verifiedVisits: 510,
      priceLevel: '$',
      address: 'Almirante Montt 420',
      district: 'Cerro Alegre',
      commune: 'Valparaíso',
      city: 'Valparaíso',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0440,
      longitude: -71.6250,
      zone: 'Cerros Porteños',
      openingHours: 'Mar - Dom: 11:00 - 19:30',
      instagram: '@cafedelapoesia',
      isFeatured: false,
      isRecommended: false,
      experienceTags: ['Café de especialidad', 'Cultura', 'Ambiente relajado']
    },

    // NEW REAL REGIONAL VENUES (VALPAR 0.4 DATA QUALITY SAMPLE - NULL RATINGS IF UNREVIEWED)
    {
      id: 'place-13',
      partnerId: null,
      status: PlaceStatus.DISCOVERED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.UNVERIFIED,
      dataSource: DataSource.PUBLIC_SOURCE,
      name: 'La Pigualia Pastelería',
      slug: 'la-pigualia-pasteleria-quilpue',
      tagline: 'Pastelería tradicional alemana en el centro de Quilpué',
      description: 'Kuchen de frutos del país, strudel de manzana y tortas artesanales.',
      category: 'Cafetería',
      subCategory: 'Pastelería Tradicional',
      categories: ['Cafetería'],
      tags: ['Kuchen', 'Quilpué', 'Pastelería'],
      imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
      rating: null,
      editorialScore: null,
      reviewCount: 0,
      verifiedVisits: 0,
      priceLevel: '$$',
      address: 'Claudio Vicuña 680',
      district: 'Centro',
      commune: 'Quilpué',
      city: 'Quilpué',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0490,
      longitude: -71.4420,
      zone: 'Marga Marga',
      openingHours: 'Lun - Sáb: 09:30 - 20:00',
      isFeatured: false,
      isRecommended: false,
      experienceTags: ['Pastelería tradicional', 'Familiar']
    },
    {
      id: 'place-14',
      partnerId: null,
      status: PlaceStatus.RECOMMENDED,
      publicationStatus: PublicationStatus.PUBLISHED,
      verificationStatus: VerificationStatus.REVIEWED,
      dataSource: DataSource.MANUAL_VALPAR,
      name: 'TRES PECES Valparaíso',
      slug: 'tres-peces-valparaiso',
      tagline: 'Restaurante de pesca responsable en Cerro Concepción',
      description: 'Pescados y mariscos comprados directamente a pescadores artesanales de Chile.',
      category: 'Restaurante',
      subCategory: 'Pesca Responsable',
      categories: ['Restaurante'],
      tags: ['Pesca responsable', 'Mariscos', 'Cerro Concepción'],
      imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
      rating: 4.9,
      editorialScore: 4.9,
      reviewCount: 290,
      verifiedVisits: 1100,
      priceLevel: '$$$',
      address: 'Abtao 644',
      district: 'Cerro Concepción',
      commune: 'Valparaíso',
      city: 'Valparaíso',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -33.0430,
      longitude: -71.6250,
      zone: 'Cerros Porteños',
      openingHours: 'Jue - Dom: 13:00 - 16:30',
      instagram: '@trespecesvalparaiso',
      isFeatured: true,
      isRecommended: true,
      experienceTags: ['Pesca sustentable', 'Gastronomía local', 'Cerro Concepción']
    },
    {
      id: 'place-15',
      partnerId: null,
      status: PlaceStatus.DISCOVERED,
      publicationStatus: PublicationStatus.DRAFT, // DRAFT status example
      verificationStatus: VerificationStatus.UNVERIFIED,
      dataSource: DataSource.API_IMPORT,
      name: 'Café Anay Zapallar',
      slug: 'cafe-anay-zapallar',
      tagline: 'Café de playa y brunch en la caleta de Zapallar',
      description: 'Café orgánico, sándwiches artesanales y alfajores de la zona costera.',
      category: 'Cafetería',
      subCategory: 'Café de Playa',
      categories: ['Cafetería'],
      tags: ['Zapallar', 'Brunch', 'Playa'],
      imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
      rating: null,
      editorialScore: null,
      reviewCount: 0,
      verifiedVisits: 0,
      priceLevel: '$$$',
      address: 'Moises Chacón 230',
      district: 'Caleta Zapallar',
      commune: 'Zapallar',
      city: 'Zapallar',
      region: 'Valparaíso',
      country: 'Chile',
      latitude: -32.5530,
      longitude: -71.4580,
      zone: 'Litoral Norte',
      openingHours: 'Lun - Dom: 09:00 - 19:00',
      isFeatured: false,
      isRecommended: false,
      experienceTags: ['Café de playa', 'Zapallar', 'Tranquilo']
    }
  ];

  for (const p of realPlacesData) {
    await prisma.place.upsert({
      where: { id: p.id },
      update: p,
      create: p
    });
  }

  // One entrance NFC tag per partner place (check-ins require an active tag).
  // update: {} keeps an existing tag's secret stable across re-seeds.
  for (const p of realPlacesData) {
    if (!p.partnerId) continue;
    await prisma.nfcTag.upsert({
      where: { id: `nfc-${p.id}` },
      update: {},
      create: {
        id: `nfc-${p.id}`,
        partnerId: p.partnerId,
        placeId: p.id,
        locationLabel: 'Entrada',
        tokenSecret: randomBytes(32).toString('hex')
      }
    });
  }

  // Create Default Users
  await prisma.user.upsert({
    where: { email: 'valentina.silva@email.cl' },
    update: {},
    create: {
      id: 'user-valpo-01',
      name: 'Valentina Silva',
      email: 'valentina.silva@email.cl',
      phone: '+56987654321',
      pointsBalance: 450,
      passportLevel: 'Explorador Porteño',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80'
    }
  });

  console.log('✅ Seed completed! 15 Real Places inserted into PostgreSQL with Data Quality standards.');
}

main()
  .catch(e => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
